"""Train and evaluate ReDoS-MotifGNN on regex HRG datasets.

The script expects datasets in TU-style folders under ``dataset/`` and a
preprocessed meta-graph pickle generated by ``preprocess.py``.  It keeps the
paper-style 10-fold stratified protocol while avoiding hard-coded dataset
sizes, devices, and result paths.
"""

from __future__ import annotations

import argparse
import json
import os
import pickle
import random
import statistics as st
import time
from datetime import datetime
from pathlib import Path

os.environ.setdefault("DGL_DISABLE_GRAPHBOLT", "1")

import dgl
import numpy as np
import torch
import torch.nn.functional as F
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import StratifiedKFold
from tqdm import tqdm

from rmgnn.data.regex_graph_loader import load_data
from rmgnn.models.rmgnn import RMGNNClassifier


OUTPUTAST_DATASETS = ("Corpus_HRG", "Csharp_HRG", "Java_HRG", "Python_HRG")
LEGACY_DATASET_ALIASES = {
    "Corpus": "Corpus_HRG",
    "Csharp": "Csharp_HRG",
    "Java": "Java_HRG",
    "Python": "Python_HRG",
}


def parse_args():
    parser = argparse.ArgumentParser(description="Train RMGNN on regex HRG datasets")
    parser.add_argument("-data", "--data", default="Corpus_HRG",
                        help="Dataset name, comma-separated names, or 'all'")
    parser.add_argument("-seed", type=int, default=14)
    parser.add_argument("--num-runs", type=int, default=1,
                        help="Number of consecutive random seeds to evaluate")
    parser.add_argument("--folds", type=int, default=10)
    parser.add_argument("--fold-limit", type=int, default=None,
                        help="Optional debug limit for folds")
    parser.add_argument("-num_epochs", "--num-epochs", type=int, default=100)
    parser.add_argument("-batch_size", "--batch-size", type=int, default=512)
    parser.add_argument("-lr", type=float, default=1e-3)
    parser.add_argument("-w_d", "--weight-decay", type=float, default=5e-4)
    parser.add_argument("-l_num", "--num-layers", type=int, default=2)
    parser.add_argument("-h_dim", "--hidden-dim", type=int, default=32)
    parser.add_argument("-drop_n", "--drop-node", type=float, default=0.2)
    parser.add_argument("-drop_c", "--drop-classifier", type=float, default=0.2)
    parser.add_argument("-device", type=int, default=0)
    parser.add_argument("--degree-as-tag", action="store_true")
    parser.add_argument("--learn-eps", action="store_true")
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--class-weight", action="store_true", default=True,
                        help="Use inverse-frequency class weights")
    parser.add_argument("--no-class-weight", dest="class_weight", action="store_false")
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument("--result-dir", default="result")
    return parser.parse_args()


def canonical_dataset_name(name: str) -> str:
    target = LEGACY_DATASET_ALIASES.get(name)
    if target is None:
        return name
    if (Path("dataset") / target).exists() or (Path("preprocessed_datasets") / target).exists():
        return target
    return name


def expand_datasets(data_arg: str):
    if data_arg.lower() == "all":
        return list(OUTPUTAST_DATASETS)
    return [canonical_dataset_name(x.strip()) for x in data_arg.split(",") if x.strip()]


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    dgl.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True


def average(values):
    return float(sum(values) / len(values)) if values else 0.0


def require_cuda_device(device_index: int) -> torch.device:
    """Return the requested CUDA device, refusing to fall back to the CPU."""
    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is not available. RMGNN training requires an NVIDIA GPU; "
            "check the NVIDIA driver and install a CUDA-enabled PyTorch build."
        )

    device_count = torch.cuda.device_count()
    if device_index < 0 or device_index >= device_count:
        raise ValueError(
            f"Invalid GPU index {device_index}; available GPU indices are "
            f"0 through {device_count - 1}."
        )

    torch.cuda.set_device(device_index)
    return torch.device(f"cuda:{device_index}")


def load_preprocessed(dataset: str):
    path = Path("preprocessed_datasets") / dataset
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Run: python preprocess.py --data {dataset}"
        )
    with path.open("rb") as source:
        saved = pickle.load(source)

    if isinstance(saved, dict):
        graph = saved["g_dgl"]
        teacher_dists = saved.get("teacher_dists", {})
        graph_count = int(saved.get("preprocess_metrics", {}).get(
            "num_input_graphs", len(teacher_dists)
        ))
    else:
        graph = saved
        teacher_dists = {}
        graph_count = 0

    if graph_count <= 0:
        label_path = Path("dataset") / dataset / "graph_labels.txt"
        graph_count = sum(1 for line in label_path.open(encoding="utf-8") if line.strip())
    return graph, teacher_dists, graph_count


def make_loaders(graph, train_idx, valid_idx, args, device):
    node_count = int(graph.num_nodes())
    train_mask = np.zeros(node_count, dtype=bool)
    valid_mask = np.zeros(node_count, dtype=bool)
    train_mask[np.asarray(train_idx)] = True
    valid_mask[np.asarray(valid_idx)] = True

    graph.ndata["train_mask"] = torch.from_numpy(train_mask).to(device)
    graph.ndata["val_mask"] = torch.from_numpy(valid_mask).to(device)

    train_nid = torch.nonzero(graph.ndata["train_mask"], as_tuple=True)[0].to(device)
    val_nid = torch.nonzero(graph.ndata["val_mask"], as_tuple=True)[0].to(device)
    sampler = dgl.dataloading.MultiLayerFullNeighborSampler(args.num_layers)

    common = {
        "device": device,
        "batch_size": args.batch_size,
        "drop_last": False,
        "num_workers": args.num_workers,
    }
    train_loader = dgl.dataloading.DataLoader(
        graph, train_nid, sampler, shuffle=True, **common
    )
    val_loader = dgl.dataloading.DataLoader(
        graph, val_nid, sampler, shuffle=False, **common
    )
    return train_loader, val_loader


def load_subtensor(features, labels, edge_weight, edge_ids, seeds, input_nodes, device):
    batch_inputs = features[input_nodes].to(device)
    batch_labels = labels[seeds].to(device)
    batch_edge_weight = [edge_weight[eid] for eid in edge_ids]
    return batch_inputs, batch_labels, batch_edge_weight


def predict_batches(model, loader, graphs, features, labels, edge_weight, num_cliques, device):
    model.eval()
    probs, trues = [], []
    infer_time = 0.0

    with torch.no_grad():
        for input_nodes, seeds, blocks in loader:
            edge_ids = [block.edata[dgl.EID] for block in blocks]
            graph_ids = [int(s.item()) for s in seeds if int(s.item()) < len(graphs)]
            batch_graphs = [graphs[i] for i in graph_ids]
            batch_inputs, batch_labels, batch_edge_weight = load_subtensor(
                features, labels, edge_weight, edge_ids, seeds, input_nodes, device
            )
            blocks = [block.int().to(device) for block in blocks]

            start = time.perf_counter()
            logits = model(blocks, batch_inputs, batch_edge_weight, batch_graphs, num_cliques)
            if device.type == "cuda":
                torch.cuda.synchronize(device)
            infer_time += time.perf_counter() - start

            logits = logits[:batch_labels.shape[0]]
            prob = F.softmax(logits, dim=1)
            probs.extend(prob[:, 1].detach().cpu().numpy())
            trues.extend(batch_labels.detach().cpu().numpy())

    return np.asarray(probs), np.asarray(trues), infer_time


def binary_metrics(trues, probs, threshold):
    preds = (probs >= threshold).astype(int)
    metrics = {
        "acc": accuracy_score(trues, preds),
        "precision": precision_score(trues, preds, zero_division=0),
        "recall": recall_score(trues, preds, zero_division=0),
        "f1": f1_score(trues, preds, zero_division=0),
    }
    try:
        metrics["ap"] = average_precision_score(trues, probs)
    except ValueError:
        metrics["ap"] = 0.0
    return metrics


def train_one_epoch(model, loader, graphs, features, labels, edge_weight,
                    num_cliques, loss_fcn, optimizer, device):
    model.train()
    correct = 0
    total = 0
    start = time.perf_counter()

    for input_nodes, seeds, blocks in loader:
        edge_ids = [block.edata[dgl.EID] for block in blocks]
        graph_ids = [int(s.item()) for s in seeds if int(s.item()) < len(graphs)]
        batch_graphs = [graphs[i] for i in graph_ids]
        batch_inputs, batch_labels, batch_edge_weight = load_subtensor(
            features, labels, edge_weight, edge_ids, seeds, input_nodes, device
        )
        blocks = [block.int().to(device) for block in blocks]
        logits = model(blocks, batch_inputs, batch_edge_weight, batch_graphs, num_cliques)
        logits = logits[:batch_labels.shape[0]]

        loss = loss_fcn(logits, batch_labels)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
        optimizer.step()

        pred = logits.argmax(dim=1)
        correct += int((pred == batch_labels).sum().item())
        total += int(batch_labels.numel())

    if device.type == "cuda":
        torch.cuda.synchronize(device)
    return correct / max(1, total), time.perf_counter() - start


def train_dataset(dataset: str, args, device):
    graph, _, graph_count = load_preprocessed(dataset)
    graph = graph.to(device)
    labels = graph.ndata["labels"].to(device)
    features = graph.ndata["feat"].to(device)
    edge_weight = graph.edata["edge_weight"].to(device)
    num_cliques = int(graph.num_nodes()) - graph_count

    graphs, num_classes = load_data(
        dataset,
        args.degree_as_tag,
        {"node_tags": {"type": "categorical", "weight": 1.0}},
        {"weight": {"type": "numeric", "range": 3.0, "weight": 1.0}},
    )
    if len(graphs) != graph_count:
        raise ValueError(
            f"{dataset}: preprocessed graph count {graph_count} != loaded graph count {len(graphs)}"
        )

    fold_count = min(args.folds, np.bincount(labels[:graph_count].detach().cpu().numpy()).min())
    if fold_count < 2:
        raise ValueError(f"{dataset}: each class needs at least two samples for CV")
    fold_limit = args.fold_limit or fold_count

    summary = []
    for seed in range(args.seed, args.seed + args.num_runs):
        set_seed(seed)
        split_labels = labels[:graph_count].detach().cpu().numpy()
        splitter = StratifiedKFold(n_splits=fold_count, shuffle=True, random_state=seed)
        fold_metrics = []

        for fold, (train_idx, valid_idx) in enumerate(splitter.split(np.zeros(graph_count), split_labels)):
            if fold >= fold_limit:
                break

            train_loader, val_loader = make_loaders(graph, train_idx, valid_idx, args, device)
            node_feat_dim = graphs[0].node_features.shape[1]
            model = RMGNNClassifier(
                args.num_layers,
                2,
                features.shape[1],
                node_feat_dim,
                args.hidden_dim,
                num_classes,
                args.drop_node,
                args.drop_classifier,
                args.learn_eps,
                "sum",
                "sum",
                device=device,
            ).to(device)

            train_labels = labels[torch.as_tensor(train_idx, device=device)].detach().cpu().numpy()
            if args.class_weight:
                counts = np.bincount(train_labels, minlength=num_classes).astype(np.float32)
                weights = counts.sum() / np.maximum(counts, 1.0)
                weights = weights / weights.mean()
            else:
                weights = np.ones(num_classes, dtype=np.float32)
            loss_fcn = torch.nn.CrossEntropyLoss(
                weight=torch.as_tensor(weights, dtype=torch.float32, device=device)
            )
            optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

            best = {"f1": -1.0}
            train_time = 0.0
            infer_time = 0.0
            for _ in tqdm(range(args.num_epochs), desc=f"{dataset} seed {seed} fold {fold}", unit="epoch"):
                train_acc, epoch_train_time = train_one_epoch(
                    model, train_loader, graphs, features, labels, edge_weight,
                    num_cliques, loss_fcn, optimizer, device
                )
                probs, trues, epoch_infer_time = predict_batches(
                    model, val_loader, graphs, features, labels, edge_weight, num_cliques, device
                )
                metrics = binary_metrics(trues, probs, args.threshold)
                metrics["train_acc"] = train_acc
                train_time += epoch_train_time
                infer_time += epoch_infer_time
                if metrics["f1"] > best["f1"] or (
                    metrics["f1"] == best["f1"] and metrics["acc"] > best.get("acc", 0.0)
                ):
                    best = metrics

            best["train_time"] = train_time
            best["infer_time"] = infer_time
            best["fold"] = fold
            fold_metrics.append(best)
            print(
                f"{dataset} fold {fold}: Acc={best['acc']:.4f} "
                f"Rec={best['recall']:.4f} "#Prec={best['precision']:.4f}
                f"F1={best['f1']:.4f} AP={best['ap']:.4f}"
            )

        seed_summary = {
            "dataset": dataset,
            "seed": seed,
            "folds": len(fold_metrics),
            "acc_mean": average([m["acc"] for m in fold_metrics]),
            "acc_std": st.stdev([m["acc"] for m in fold_metrics]) if len(fold_metrics) > 1 else 0.0,
            "precision_mean": average([m["precision"] for m in fold_metrics]),
            "recall_mean": average([m["recall"] for m in fold_metrics]),
            "f1_mean": average([m["f1"] for m in fold_metrics]),
            "ap_mean": average([m["ap"] for m in fold_metrics]),
            "train_time_mean": average([m["train_time"] for m in fold_metrics]),
            "infer_time_mean": average([m["infer_time"] for m in fold_metrics]),
        }
        summary.append(seed_summary)
        print(
            f"{dataset} seed {seed}: Acc={seed_summary['acc_mean']:.5f}"
            f"+/-{seed_summary['acc_std']:.5f} F1={seed_summary['f1_mean']:.5f} "
            f"AP={seed_summary['ap_mean']:.5f}"
        )
    return summary


def main():
    args = parse_args()
    device = require_cuda_device(args.device)
    print(f"Using GPU {args.device}: {torch.cuda.get_device_name(args.device)}")
    Path(args.result_dir).mkdir(parents=True, exist_ok=True)

    all_results = []
    for dataset in expand_datasets(args.data):
        all_results.extend(train_dataset(dataset, args, device))

    stamp = datetime.now().strftime("%Y%m%d%H%M%S")
    result_path = Path(args.result_dir) / f"rmgnn_results_{stamp}.json"
    with result_path.open("w", encoding="utf-8") as target:
        json.dump(all_results, target, indent=2)
    print(f"Saved results to {result_path}")


if __name__ == "__main__":
    main()
